# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.repo_api import RepoApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestRepoApi(unittest.TestCase):
    """RepoApi unit test stubs"""

    def setUp(self):
        self.api = RepoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_visible(self):
        """Test case for change_visible

        change repository visible(true for public, false for private)  # noqa: E501
        """
        pass

    def test_create_repository(self):
        """Test case for create_repository

        create repository  # noqa: E501
        """
        pass

    def test_delete_repository(self):
        """Test case for delete_repository

        delete repository  # noqa: E501
        """
        pass

    def test_get_commits_in_ref(self):
        """Test case for get_commits_in_ref

        get commits in ref  # noqa: E501
        """
        pass

    def test_get_repository(self):
        """Test case for get_repository

        get repository  # noqa: E501
        """
        pass

    def test_list_public_repository(self):
        """Test case for list_public_repository

        list public repository in all system  # noqa: E501
        """
        pass

    def test_list_repository(self):
        """Test case for list_repository

        list repository in specific owner  # noqa: E501
        """
        pass

    def test_list_repository_of_authenticated_user(self):
        """Test case for list_repository_of_authenticated_user

        list repository  # noqa: E501
        """
        pass

    def test_update_repository(self):
        """Test case for update_repository

        update repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
