# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.models.setup_state import SetupState  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestSetupState(unittest.TestCase):
    """SetupState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetupState(self):
        """Test SetupState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jiaozifs_client.models.setup_state.SetupState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
