# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.mergerequest_api import MergerequestApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestMergerequestApi(unittest.TestCase):
    """MergerequestApi unit test stubs"""

    def setUp(self):
        self.api = MergerequestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_merge_request(self):
        """Test case for create_merge_request

        create merge request  # noqa: E501
        """
        pass

    def test_get_merge_request(self):
        """Test case for get_merge_request

        get merge request  # noqa: E501
        """
        pass

    def test_list_merge_requests(self):
        """Test case for list_merge_requests

        get list of merge request in repository  # noqa: E501
        """
        pass

    def test_merge(self):
        """Test case for merge

        merge a mergerequest  # noqa: E501
        """
        pass

    def test_update_merge_request(self):
        """Test case for update_merge_request

        update merge request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
