# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.auth_api import AuthApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        get information of the currently logged-in user  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        perform a login  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        perform a logout  # noqa: E501
        """
        pass

    def test_refresh_token(self):
        """Test case for refresh_token

        refresh token for more time  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        perform user registration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
