# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.commit_api import CommitApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestCommitApi(unittest.TestCase):
    """CommitApi unit test stubs"""

    def setUp(self):
        self.api = CommitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compare_commit(self):
        """Test case for compare_commit

        compare two commit  # noqa: E501
        """
        pass

    def test_get_commit_changes(self):
        """Test case for get_commit_changes

        get changes in commit  # noqa: E501
        """
        pass

    def test_get_entries_in_ref(self):
        """Test case for get_entries_in_ref

        list entries in ref  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
