# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.wip_api import WipApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestWipApi(unittest.TestCase):
    """WipApi unit test stubs"""

    def setUp(self):
        self.api = WipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_commit_wip(self):
        """Test case for commit_wip

        commit working in process to branch  # noqa: E501
        """
        pass

    def test_delete_wip(self):
        """Test case for delete_wip

        remove working in process  # noqa: E501
        """
        pass

    def test_get_wip(self):
        """Test case for get_wip

        get working in process  # noqa: E501
        """
        pass

    def test_get_wip_changes(self):
        """Test case for get_wip_changes

        get working in process changes  # noqa: E501
        """
        pass

    def test_list_wip(self):
        """Test case for list_wip

        list wip in specific project and user  # noqa: E501
        """
        pass

    def test_revert_wip_changes(self):
        """Test case for revert_wip_changes

        revert changes in working in process, empty path will revert all  # noqa: E501
        """
        pass

    def test_update_wip(self):
        """Test case for update_wip

        update wip  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
