# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.objects_api import ObjectsApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self):
        self.api = ObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_object(self):
        """Test case for delete_object

        delete object. Missing objects will not return a NotFound error.  # noqa: E501
        """
        pass

    def test_get_files(self):
        """Test case for get_files

        get files by pattern  # noqa: E501
        """
        pass

    def test_get_object(self):
        """Test case for get_object

        get object content  # noqa: E501
        """
        pass

    def test_head_object(self):
        """Test case for head_object

        check if object exists  # noqa: E501
        """
        pass

    def test_upload_object(self):
        """Test case for upload_object

        """
        pass


if __name__ == '__main__':
    unittest.main()
