# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.models.merge_request import MergeRequest  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestMergeRequest(unittest.TestCase):
    """MergeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMergeRequest(self):
        """Test MergeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jiaozifs_client.models.merge_request.MergeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
