# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.aksks_api import AksksApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestAksksApi(unittest.TestCase):
    """AksksApi unit test stubs"""

    def setUp(self):
        self.api = AksksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_aksk(self):
        """Test case for create_aksk

        create aksk  # noqa: E501
        """
        pass

    def test_delete_aksk(self):
        """Test case for delete_aksk

        delete aksk  # noqa: E501
        """
        pass

    def test_get_aksk(self):
        """Test case for get_aksk

        get aksk  # noqa: E501
        """
        pass

    def test_list_aksks(self):
        """Test case for list_aksks

        list aksks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
