# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.common_api import CommonApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestCommonApi(unittest.TestCase):
    """CommonApi unit test stubs"""

    def setUp(self):
        self.api = CommonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_setup_state(self):
        """Test case for get_setup_state

        check if jiaozifs setup  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        return program and runtime version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
