# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jiaozifs_client
from jiaozifs_client.api.branches_api import BranchesApi  # noqa: E501
from jiaozifs_client.rest import ApiException


class TestBranchesApi(unittest.TestCase):
    """BranchesApi unit test stubs"""

    def setUp(self):
        self.api = BranchesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_branch(self):
        """Test case for create_branch

        create branch  # noqa: E501
        """
        pass

    def test_delete_branch(self):
        """Test case for delete_branch

        delete branch  # noqa: E501
        """
        pass

    def test_get_branch(self):
        """Test case for get_branch

        get branch  # noqa: E501
        """
        pass

    def test_list_branches(self):
        """Test case for list_branches

        list branches  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
