# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthenticationToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'token_expiration': 'int'
    }

    attribute_map = {
        'token': 'token',
        'token_expiration': 'token_expiration'
    }

    def __init__(self, token=None, token_expiration=None):  # noqa: E501
        """AuthenticationToken - a model defined in Swagger"""  # noqa: E501
        self._token = None
        self._token_expiration = None
        self.discriminator = None
        self.token = token
        if token_expiration is not None:
            self.token_expiration = token_expiration

    @property
    def token(self):
        """Gets the token of this AuthenticationToken.  # noqa: E501

        a JWT token that could be used to authenticate requests  # noqa: E501

        :return: The token of this AuthenticationToken.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this AuthenticationToken.

        a JWT token that could be used to authenticate requests  # noqa: E501

        :param token: The token of this AuthenticationToken.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def token_expiration(self):
        """Gets the token_expiration of this AuthenticationToken.  # noqa: E501

        Unix Epoch in seconds  # noqa: E501

        :return: The token_expiration of this AuthenticationToken.  # noqa: E501
        :rtype: int
        """
        return self._token_expiration

    @token_expiration.setter
    def token_expiration(self, token_expiration):
        """Sets the token_expiration of this AuthenticationToken.

        Unix Epoch in seconds  # noqa: E501

        :param token_expiration: The token_expiration of this AuthenticationToken.  # noqa: E501
        :type: int
        """

        self._token_expiration = token_expiration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticationToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticationToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
