# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Change(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'action': 'int',
        'base_hash': 'str',
        'to_hash': 'str'
    }

    attribute_map = {
        'path': 'path',
        'action': 'action',
        'base_hash': 'base_hash',
        'to_hash': 'to_hash'
    }

    def __init__(self, path=None, action=None, base_hash=None, to_hash=None):  # noqa: E501
        """Change - a model defined in Swagger"""  # noqa: E501
        self._path = None
        self._action = None
        self._base_hash = None
        self._to_hash = None
        self.discriminator = None
        self.path = path
        self.action = action
        if base_hash is not None:
            self.base_hash = base_hash
        if to_hash is not None:
            self.to_hash = to_hash

    @property
    def path(self):
        """Gets the path of this Change.  # noqa: E501


        :return: The path of this Change.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this Change.


        :param path: The path of this Change.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def action(self):
        """Gets the action of this Change.  # noqa: E501


        :return: The action of this Change.  # noqa: E501
        :rtype: int
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this Change.


        :param action: The action of this Change.  # noqa: E501
        :type: int
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501
        allowed_values = [1, 2, 3]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def base_hash(self):
        """Gets the base_hash of this Change.  # noqa: E501


        :return: The base_hash of this Change.  # noqa: E501
        :rtype: str
        """
        return self._base_hash

    @base_hash.setter
    def base_hash(self, base_hash):
        """Sets the base_hash of this Change.


        :param base_hash: The base_hash of this Change.  # noqa: E501
        :type: str
        """

        self._base_hash = base_hash

    @property
    def to_hash(self):
        """Gets the to_hash of this Change.  # noqa: E501


        :return: The to_hash of this Change.  # noqa: E501
        :rtype: str
        """
        return self._to_hash

    @to_hash.setter
    def to_hash(self, to_hash):
        """Sets the to_hash of this Change.


        :param to_hash: The to_hash of this Change.  # noqa: E501
        :type: str
        """

        self._to_hash = to_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Change, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Change):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
