# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateMergeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target_branch_name': 'str',
        'source_branch_name': 'str',
        'title': 'str',
        'description': 'str'
    }

    attribute_map = {
        'target_branch_name': 'target_branch_name',
        'source_branch_name': 'source_branch_name',
        'title': 'title',
        'description': 'description'
    }

    def __init__(self, target_branch_name=None, source_branch_name=None, title=None, description=None):  # noqa: E501
        """CreateMergeRequest - a model defined in Swagger"""  # noqa: E501
        self._target_branch_name = None
        self._source_branch_name = None
        self._title = None
        self._description = None
        self.discriminator = None
        self.target_branch_name = target_branch_name
        self.source_branch_name = source_branch_name
        self.title = title
        if description is not None:
            self.description = description

    @property
    def target_branch_name(self):
        """Gets the target_branch_name of this CreateMergeRequest.  # noqa: E501


        :return: The target_branch_name of this CreateMergeRequest.  # noqa: E501
        :rtype: str
        """
        return self._target_branch_name

    @target_branch_name.setter
    def target_branch_name(self, target_branch_name):
        """Sets the target_branch_name of this CreateMergeRequest.


        :param target_branch_name: The target_branch_name of this CreateMergeRequest.  # noqa: E501
        :type: str
        """
        if target_branch_name is None:
            raise ValueError("Invalid value for `target_branch_name`, must not be `None`")  # noqa: E501

        self._target_branch_name = target_branch_name

    @property
    def source_branch_name(self):
        """Gets the source_branch_name of this CreateMergeRequest.  # noqa: E501


        :return: The source_branch_name of this CreateMergeRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_branch_name

    @source_branch_name.setter
    def source_branch_name(self, source_branch_name):
        """Sets the source_branch_name of this CreateMergeRequest.


        :param source_branch_name: The source_branch_name of this CreateMergeRequest.  # noqa: E501
        :type: str
        """
        if source_branch_name is None:
            raise ValueError("Invalid value for `source_branch_name`, must not be `None`")  # noqa: E501

        self._source_branch_name = source_branch_name

    @property
    def title(self):
        """Gets the title of this CreateMergeRequest.  # noqa: E501


        :return: The title of this CreateMergeRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateMergeRequest.


        :param title: The title of this CreateMergeRequest.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this CreateMergeRequest.  # noqa: E501


        :return: The description of this CreateMergeRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateMergeRequest.


        :param description: The description of this CreateMergeRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateMergeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateMergeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
