# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Credential(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_key_id': 'SecureString',
        'secret_access_key': 'SecureString',
        'session_token': 'SecureString'
    }

    attribute_map = {
        'access_key_id': 'access_key_id',
        'secret_access_key': 'secret_access_key',
        'session_token': 'session_token'
    }

    def __init__(self, access_key_id=None, secret_access_key=None, session_token=None):  # noqa: E501
        """Credential - a model defined in Swagger"""  # noqa: E501
        self._access_key_id = None
        self._secret_access_key = None
        self._session_token = None
        self.discriminator = None
        self.access_key_id = access_key_id
        self.secret_access_key = secret_access_key
        self.session_token = session_token

    @property
    def access_key_id(self):
        """Gets the access_key_id of this Credential.  # noqa: E501


        :return: The access_key_id of this Credential.  # noqa: E501
        :rtype: SecureString
        """
        return self._access_key_id

    @access_key_id.setter
    def access_key_id(self, access_key_id):
        """Sets the access_key_id of this Credential.


        :param access_key_id: The access_key_id of this Credential.  # noqa: E501
        :type: SecureString
        """
        if access_key_id is None:
            raise ValueError("Invalid value for `access_key_id`, must not be `None`")  # noqa: E501

        self._access_key_id = access_key_id

    @property
    def secret_access_key(self):
        """Gets the secret_access_key of this Credential.  # noqa: E501


        :return: The secret_access_key of this Credential.  # noqa: E501
        :rtype: SecureString
        """
        return self._secret_access_key

    @secret_access_key.setter
    def secret_access_key(self, secret_access_key):
        """Sets the secret_access_key of this Credential.


        :param secret_access_key: The secret_access_key of this Credential.  # noqa: E501
        :type: SecureString
        """
        if secret_access_key is None:
            raise ValueError("Invalid value for `secret_access_key`, must not be `None`")  # noqa: E501

        self._secret_access_key = secret_access_key

    @property
    def session_token(self):
        """Gets the session_token of this Credential.  # noqa: E501


        :return: The session_token of this Credential.  # noqa: E501
        :rtype: SecureString
        """
        return self._session_token

    @session_token.setter
    def session_token(self, session_token):
        """Sets the session_token of this Credential.


        :param session_token: The session_token of this Credential.  # noqa: E501
        :type: SecureString
        """
        if session_token is None:
            raise ValueError("Invalid value for `session_token`, must not be `None`")  # noqa: E501

        self._session_token = session_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Credential, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Credential):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
