# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MergeMergeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'msg': 'str',
        'conflict_resolve': 'dict(str, str)'
    }

    attribute_map = {
        'msg': 'msg',
        'conflict_resolve': 'conflict_resolve'
    }

    def __init__(self, msg=None, conflict_resolve=None):  # noqa: E501
        """MergeMergeRequest - a model defined in Swagger"""  # noqa: E501
        self._msg = None
        self._conflict_resolve = None
        self.discriminator = None
        self.msg = msg
        if conflict_resolve is not None:
            self.conflict_resolve = conflict_resolve

    @property
    def msg(self):
        """Gets the msg of this MergeMergeRequest.  # noqa: E501


        :return: The msg of this MergeMergeRequest.  # noqa: E501
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this MergeMergeRequest.


        :param msg: The msg of this MergeMergeRequest.  # noqa: E501
        :type: str
        """
        if msg is None:
            raise ValueError("Invalid value for `msg`, must not be `None`")  # noqa: E501

        self._msg = msg

    @property
    def conflict_resolve(self):
        """Gets the conflict_resolve of this MergeMergeRequest.  # noqa: E501

        use to record the resolution of the conflict, example({\"b/a.txt\":\"left\"})  # noqa: E501

        :return: The conflict_resolve of this MergeMergeRequest.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._conflict_resolve

    @conflict_resolve.setter
    def conflict_resolve(self, conflict_resolve):
        """Sets the conflict_resolve of this MergeMergeRequest.

        use to record the resolution of the conflict, example({\"b/a.txt\":\"left\"})  # noqa: E501

        :param conflict_resolve: The conflict_resolve of this MergeMergeRequest.  # noqa: E501
        :type: dict(str, str)
        """

        self._conflict_resolve = conflict_resolve

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MergeMergeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MergeMergeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
