# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateWip(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_commit': 'str',
        'current_tree': 'str'
    }

    attribute_map = {
        'base_commit': 'base_commit',
        'current_tree': 'current_tree'
    }

    def __init__(self, base_commit=None, current_tree=None):  # noqa: E501
        """UpdateWip - a model defined in Swagger"""  # noqa: E501
        self._base_commit = None
        self._current_tree = None
        self.discriminator = None
        if base_commit is not None:
            self.base_commit = base_commit
        if current_tree is not None:
            self.current_tree = current_tree

    @property
    def base_commit(self):
        """Gets the base_commit of this UpdateWip.  # noqa: E501


        :return: The base_commit of this UpdateWip.  # noqa: E501
        :rtype: str
        """
        return self._base_commit

    @base_commit.setter
    def base_commit(self, base_commit):
        """Sets the base_commit of this UpdateWip.


        :param base_commit: The base_commit of this UpdateWip.  # noqa: E501
        :type: str
        """

        self._base_commit = base_commit

    @property
    def current_tree(self):
        """Gets the current_tree of this UpdateWip.  # noqa: E501


        :return: The current_tree of this UpdateWip.  # noqa: E501
        :rtype: str
        """
        return self._current_tree

    @current_tree.setter
    def current_tree(self, current_tree):
        """Sets the current_tree of this UpdateWip.


        :param current_tree: The current_tree of this UpdateWip.  # noqa: E501
        :type: str
        """

        self._current_tree = current_tree

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateWip, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateWip):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
