# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'email': 'str',
        'current_sign_in_at': 'int',
        'last_sign_in_at': 'int',
        'current_sign_in_ip': 'str',
        'last_sign_in_ip': 'str',
        'created_at': 'int',
        'updated_at': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'email': 'email',
        'current_sign_in_at': 'current_sign_in_at',
        'last_sign_in_at': 'last_sign_in_at',
        'current_sign_in_ip': 'current_sign_in_ip',
        'last_sign_in_ip': 'last_sign_in_ip',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, name=None, email=None, current_sign_in_at=None, last_sign_in_at=None, current_sign_in_ip=None, last_sign_in_ip=None, created_at=None, updated_at=None):  # noqa: E501
        """UserInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._email = None
        self._current_sign_in_at = None
        self._last_sign_in_at = None
        self._current_sign_in_ip = None
        self._last_sign_in_ip = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.email = email
        if current_sign_in_at is not None:
            self.current_sign_in_at = current_sign_in_at
        if last_sign_in_at is not None:
            self.last_sign_in_at = last_sign_in_at
        if current_sign_in_ip is not None:
            self.current_sign_in_ip = current_sign_in_ip
        if last_sign_in_ip is not None:
            self.last_sign_in_ip = last_sign_in_ip
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this UserInfo.  # noqa: E501


        :return: The id of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserInfo.


        :param id: The id of this UserInfo.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this UserInfo.  # noqa: E501


        :return: The name of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserInfo.


        :param name: The name of this UserInfo.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def email(self):
        """Gets the email of this UserInfo.  # noqa: E501


        :return: The email of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserInfo.


        :param email: The email of this UserInfo.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def current_sign_in_at(self):
        """Gets the current_sign_in_at of this UserInfo.  # noqa: E501


        :return: The current_sign_in_at of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._current_sign_in_at

    @current_sign_in_at.setter
    def current_sign_in_at(self, current_sign_in_at):
        """Sets the current_sign_in_at of this UserInfo.


        :param current_sign_in_at: The current_sign_in_at of this UserInfo.  # noqa: E501
        :type: int
        """

        self._current_sign_in_at = current_sign_in_at

    @property
    def last_sign_in_at(self):
        """Gets the last_sign_in_at of this UserInfo.  # noqa: E501


        :return: The last_sign_in_at of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._last_sign_in_at

    @last_sign_in_at.setter
    def last_sign_in_at(self, last_sign_in_at):
        """Sets the last_sign_in_at of this UserInfo.


        :param last_sign_in_at: The last_sign_in_at of this UserInfo.  # noqa: E501
        :type: int
        """

        self._last_sign_in_at = last_sign_in_at

    @property
    def current_sign_in_ip(self):
        """Gets the current_sign_in_ip of this UserInfo.  # noqa: E501


        :return: The current_sign_in_ip of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._current_sign_in_ip

    @current_sign_in_ip.setter
    def current_sign_in_ip(self, current_sign_in_ip):
        """Sets the current_sign_in_ip of this UserInfo.


        :param current_sign_in_ip: The current_sign_in_ip of this UserInfo.  # noqa: E501
        :type: str
        """

        self._current_sign_in_ip = current_sign_in_ip

    @property
    def last_sign_in_ip(self):
        """Gets the last_sign_in_ip of this UserInfo.  # noqa: E501


        :return: The last_sign_in_ip of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._last_sign_in_ip

    @last_sign_in_ip.setter
    def last_sign_in_ip(self, last_sign_in_ip):
        """Sets the last_sign_in_ip of this UserInfo.


        :param last_sign_in_ip: The last_sign_in_ip of this UserInfo.  # noqa: E501
        :type: str
        """

        self._last_sign_in_ip = last_sign_in_ip

    @property
    def created_at(self):
        """Gets the created_at of this UserInfo.  # noqa: E501


        :return: The created_at of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this UserInfo.


        :param created_at: The created_at of this UserInfo.  # noqa: E501
        :type: int
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this UserInfo.  # noqa: E501


        :return: The updated_at of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this UserInfo.


        :param updated_at: The updated_at of this UserInfo.  # noqa: E501
        :type: int
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
