# coding: utf-8

"""
    jiaozifs API

    jiaozifs HTTP API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebIdentity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_duration': 'int',
        'session_expiry_window': 'int'
    }

    attribute_map = {
        'session_duration': 'session_duration',
        'session_expiry_window': 'session_expiry_window'
    }

    def __init__(self, session_duration=None, session_expiry_window=None):  # noqa: E501
        """WebIdentity - a model defined in Swagger"""  # noqa: E501
        self._session_duration = None
        self._session_expiry_window = None
        self.discriminator = None
        self.session_duration = session_duration
        self.session_expiry_window = session_expiry_window

    @property
    def session_duration(self):
        """Gets the session_duration of this WebIdentity.  # noqa: E501


        :return: The session_duration of this WebIdentity.  # noqa: E501
        :rtype: int
        """
        return self._session_duration

    @session_duration.setter
    def session_duration(self, session_duration):
        """Sets the session_duration of this WebIdentity.


        :param session_duration: The session_duration of this WebIdentity.  # noqa: E501
        :type: int
        """
        if session_duration is None:
            raise ValueError("Invalid value for `session_duration`, must not be `None`")  # noqa: E501

        self._session_duration = session_duration

    @property
    def session_expiry_window(self):
        """Gets the session_expiry_window of this WebIdentity.  # noqa: E501


        :return: The session_expiry_window of this WebIdentity.  # noqa: E501
        :rtype: int
        """
        return self._session_expiry_window

    @session_expiry_window.setter
    def session_expiry_window(self, session_expiry_window):
        """Sets the session_expiry_window of this WebIdentity.


        :param session_expiry_window: The session_expiry_window of this WebIdentity.  # noqa: E501
        :type: int
        """
        if session_expiry_window is None:
            raise ValueError("Invalid value for `session_expiry_window`, must not be `None`")  # noqa: E501

        self._session_expiry_window = session_expiry_window

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebIdentity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebIdentity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
